version: "3.7"

services:
  #MariaDB
  db:
    image: postgres:13
    ports:
      - '54321:5432'
    container_name: '${PROJECT_NAME}_db'
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/data/dump:/app/dump
      - ./docker/data/postgresql:/var/lib/postgresql/data
    networks:
      - local-network
  #PHP-FPM
  app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: ./
      dockerfile: docker/app.Dockerfile
    volumes:
      - ./:/app
      - ~/.composer:/var/www/.composer
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
    networks:
      - local-network

  #NginX
  web:
    container_name: ${PROJECT_NAME}_web
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    volumes:
      - ./docker/config/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
            - "8081:80"
    networks:
      - local-network
#Docker Networks
networks:
  local-network:
    driver: bridge
